## Script to calculate albedo estimates for each relevant SustHerb site
## This script uses the albedo model generated by Cherubini et al. 


##PACKAGES ----------------------------------------------------------------------------------------

        #Packages for general data manipulation + visualization
        library(ggplot2)
        library(dplyr)
        library(RColorBrewer)
        library(wesanderson)
        library(sp)
        library(raster)
        library(GGally)
        library(lattice)

###END PACKAGES ----------------------------------------------------------------------------------------




#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\




#INITIAL DATA IMPORT + FORMATTING ----------------------------------------------------------------------

        ## SITE DATA

                #Get 'cleaned' site data from adjacent 'Sites' folder
                site_data <- read.csv('1_Albedo_Exclosures/Data/SustHerb_Site_Data/cleaned_data/cleaned_data.csv', header = TRUE)

        ## SUBPLOT VOLUMES
                
                #Get plot volume estimates
                plot_volumes <- read.csv('1_Albedo_Exclosures/Approach_1/Output/Tree_Volumes/tree_volumes_approach_1.csv', header = TRUE)
                
                #Fix Singsås string
                plot_volumes$LocalityName[plot_volumes$LocalityName == "singsås"] <- "singsaas"
        
        ## SENORGE SWE/TEMP DATA
                
                #Add monthly SWE averages from seNorge
                swe <- read.csv('1_Albedo_Exclosures/Universal/Output/SWE/monthly_avg_swe_mm.csv', header = TRUE)
                
                #Add monthly temperature averages from seNorge
                temps <- read.csv('1_Albedo_Exclosures/Universal/Output/Temperature/monthly_avg_temp_C.csv', header = TRUE)
                
                        #Convert temps from celsius (C) to kelvin (K)
                        for( i in 1:length(temps$X)){
                                #K = C + 273.15
                                temps[i, "Avg_Temp_C"] <- temps[i, "Avg_Temp_C"] + 273.15
                        }
                
                        #Rename column from C to K
                        colnames(temps)[9] <- "Avg_Temps_K"
                        
        #HERBIVORE DENSITY DATA
                        
                #Read in herbivore biomass data (2015) from SpatialPolygons object (isolate dataframe)
                hbiomass_shp <- shapefile("2_Albedo_Regional/Data/Herbivore_Densities/NorwayLargeHerbivores")
                
                #Pull out dataframe
                hbiomass <- hbiomass_shp@data
                
                #Isolate to 2015 data
                hbiomass2015<- cbind(hbiomass[,c(1:10)], hbiomass$Ms_2015, hbiomass$Rd__2015, hbiomass$R_d_2015)
                        
        ## SUSTHERB SITE PRODUCTIVITY
                        
                #Productivity Data
                productivity <- read.csv('1_Albedo_Exclosures/Data/SustHerb_Site_Data/productivity_all_sites.csv', header = TRUE)
                productivity$LocalityName <- tolower(productivity$LocalityName)
                
                        #Correct LocalityName items in productivity CSV
                        
                                #Didrik Holmsen
                                productivity$LocalityName[productivity$LocalityName == "didrik holmsen"] <- "didrik_holmsen"
                                
                                #Fet 3
                                productivity$LocalityName[productivity$LocalityName == "fet 3"] <- "fet_3"
                                
                                #Fritsøe 1
                                productivity$LocalityName[productivity$LocalityName == "fritsøe1"] <- "fritsoe1"
                                
                                #Fritsøe 2
                                productivity$LocalityName[productivity$LocalityName == "fritsøe2"] <- "fritsoe2"
                                
                                #Halvard Pramhus
                                productivity$LocalityName[productivity$LocalityName == "halvard pramhus"] <- "halvard_pramhus"
                                
                                #Singsaas
                                productivity$LocalityName[productivity$LocalityName == "singsås"] <- "singsaas"
                                
                                #Stangeskovene Aurskog
                                productivity$LocalityName[productivity$LocalityName == "stangeskovene aurskog"] <- "stangeskovene_aurskog"
                                
                                #Stangeskovene Eidskog
                                productivity$LocalityName[productivity$LocalityName == "stangeskovene eidskog"] <- "stangeskovene_eidskog"
                                
                                #Stig Dahlen
                                productivity$LocalityName[productivity$LocalityName == "stig dæhlen"] <- "stig_dahlen"
                                
                                #Truls Holm
                                productivity$LocalityName[productivity$LocalityName == "truls holm"] <- "truls_holm"
        
        ## SUSTHERB TREE SPECIES PROPORTIONS (At the PLOT level)
        
                #Tree density data for Trøndelag, Telemark, and Hedmark (including 2019 data)
                tree_data <- read.csv('1_Albedo_Exclosures/Universal/Output/Tree_Species_Proportions/tree_species_proportions_plot_level.csv', header = TRUE)
                tree_data <- tree_data[,2:7]
                
                #Filter tree data to 2016 (to correspond with detailed SUSTHERB tree data)
                tree_data <- tree_data[tree_data$Year == 2016,]

                        #Filter out unused SustHerb sites (since detailed 2016 tree data is only available in Trondelag)
                
                                #Convert site codes to factors
                                tree_data$LocalityCode <- as.factor(tree_data$LocalityCode)
                                plot_volumes$LocalityCode <- as.factor(plot_volumes$LocalityCode)
                                
                                #Get vector of levels for sites that will be used (n = 74)
                                used_sites <- levels(plot_volumes$LocalityCode)
                        
                                #Filter tree data to used sites
                                tree_data <- tree_data[tree_data$LocalityCode %in% used_sites,]
                                tree_data$LocalityCode <- as.factor(as.character(tree_data$LocalityCode))
                        
                
#END INITIAL DATA IMPORT + FORMATTING ------------------------------------------------------------------

        


#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\




#CALCULATE MONTHLY ALBEDOS -----------------------------------------------------------------------------
        
        #Albedo function
                                
                #Source albedo model function
                source("3_Albedo_Model/albedo_model_volume.R")
                                
                #Blank dataframe to hold final albedo values
                albedo2 <- data.frame("Month" = double(), "Composite_Albedo" = double(), "LocalityCode" = factor())
                                
                #For each site, run albedo model function w/ relevant arguments
                for(i in 1:length(plot_volumes$LocalityCode)){
                        
                        #Get site code
                        a <- plot_volumes[i, "LocalityCode"]
                        
                        #Get site name
                        b <- plot_volumes[i, "LocalityName"]
                        
                        #Get treatment
                        c <- plot_volumes[i, "Treatment"]
                        
                        #Get corresponding function arguments
                        
                                #Volume
                                a_vol <- plot_volumes$Volume_m3[plot_volumes$LocalityCode == a]
                                
                                #Spruce %
                                a_spruce <- tree_data$Prop_spruce[tree_data$LocalityCode == a]
                                
                                #Pine %
                                a_pine <- tree_data$Prop_pine[tree_data$LocalityCode == a]
                                
                                #Birch/Deciduous %
                                a_birch <- tree_data$Prop_birch[tree_data$LocalityCode == a]
                                
                                #NOTE: The SWE and Temp datasets only have data for the 'browsed' plots
                                ## However, it is assuemd that the exclosures have the same SWE & Temp data
                                ### The code below handles this issue - for all exclosures, SWE/Temp data
                                #### from open plots is used
                                
                                        #If exclosure, get LocalityCode for corresponding open plot
                                        if(c == "UB"){
                                                
                                              d <- plot_volumes$LocalityCode[plot_volumes$LocalityName == b & plot_volumes$Treatment == 'B']
                                              
                                              #Temps
                                              a_temps <- temps$Avg_Temps_K[temps$LocalityCode == d]
                                              
                                              #SWE
                                              a_swe <- swe$SWE_mm[swe$LocalityCode == d]
                                                      
                                        } else if (c == "B"){
                                                
                                                #Temps
                                                a_temps <- temps$Avg_Temps_K[temps$LocalityCode == a]
                                                
                                                #SWE
                                                a_swe <- swe$SWE_mm[swe$LocalityCode == a]
                                        }
                                
                                
                        #Run function with necessary arguments
                        albedo1 <- albedoVol(site = a,
                                             localityName = b,
                                             treatment = c,
                                             vol = a_vol,
                                             temp = a_temps,
                                             swe = a_swe,
                                             spruce = a_spruce,
                                             pine = a_pine,
                                             birch = a_birch)
                        
                        albedo2 <- rbind(albedo2, albedo1)
                        
                }
                                
#END CALCULATE MONTHLY ALBEDOS -------------------------------------------------------------------------
                
                
                

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\




#EXPLORE DATA -----------------------------------------------------------------------------

        ##Coalesce all data into single dataframe (for analysis)
                
                #Add new columns
                albedo2$Region = ''
                albedo2$Years_Since_Clearcut = ''
                albedo2$Productivity_Index = ''
                albedo2$Moose_Density = ''
                albedo2$Red_Deer_Density = ''
                albedo2$Roe_Deer_Density = ''
                albedo2$Canopy_Height_MAD = ''
                
                #Define 'model_data' df for analysis
                model_data <- albedo2
                
                #Add relevant data for new columns
                for(i in 1:nrow(model_data)){
                        
                        print(i)
                        
                        #Get locality code
                        loc <- model_data[i, "LocalityCode"]
                        
                        #Get site name
                        sn <- model_data[i, "LocalityName"]
                        
                        #Get kommune number
                        kn <- site_data$DistrictID[site_data$LocalityCode == loc]
                        
                        #Get corresponding 'region' from site data & add
                        region <- site_data$Region[site_data$LocalityCode == loc]
                        model_data[i, "Region"] <- region
                        
                        #Get corresponding 'productivity' & add
                        prod <- productivity$Productivity[productivity$LocalityName == sn]
                        model_data[i, "Productivity_Index"] <- prod
                        
                        #Get 'Years Since Clearcut' number & add
                        ccl <- site_data$Clear.cut[site_data$LocalityCode == loc]
                        ccl <- 2016 - ccl
                        model_data[i, "Years_Since_Clearcut"] <- ccl
                        
                        #Get canopy height MAD & add
                        mad <- site_data$MAD[site_data$LocalityCode == loc]
                        model_data[i, "Canopy_Height_MAD"] <- mad
                        
                        #Get 2015 herbivore densities and add
                        
                                #Moose density
                                md <- hbiomass2015$`hbiomass$Ms_2015`[hbiomass2015$KOMMUNE == kn]
                                model_data[i, "Moose_Density"] <- md
                                
                                #Red deer density
                                rd <- hbiomass2015$`hbiomass$Rd__2015`[hbiomass2015$KOMMUNE == kn]
                                model_data[i, "Red_Deer_Density"] <- rd
                                
                                #Roe deer density
                                rdd <- hbiomass2015$`hbiomass$R_d_2015`[hbiomass2015$KOMMUNE == kn]
                                model_data[i, "Roe_Deer_Density"] <- rdd
                        
                }
                
                model_data$Treatment <- as.factor(model_data$Treatment)
                model_data$Productivity_Index <- as.numeric(model_data$Productivity_Index)
                model_data$Month <- as.numeric(model_data$Month)
                model_data$LocalityCode <- as.character(model_data$LocalityCode)
                model_data$Years_Since_Clearcut <- as.numeric(model_data$Years_Since_Clearcut)
                model_data$Moose_Density <- as.numeric(model_data$Moose_Density)
                model_data$Red_Deer_Density <- as.numeric(model_data$Red_Deer_Density)
                model_data$Roe_Deer_Density <- as.numeric(model_data$Roe_Deer_Density)
                model_data$Canopy_Height_MAD <- as.numeric(model_data$Canopy_Height_MAD)

        ##Explore data w/ plots
                        
                ##Bar plot of final albedo values, by treatment
                model_plot1 <- ggplot(data = model_data, aes(x = Treatment, y = Composite_Albedo, fill = Treatment)) +
                        geom_boxplot() +
                        ggtitle("Range of albedo estimates for SustHerb study sites") +
                        labs(x = "Site Treatment", y = "Albedo") +
                        scale_fill_manual(values=wes_palette(n=2, name="FantasticFox1")) +
                        theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                              legend.position = "none",
                              axis.text.x = element_text(size = 44, margin = margin(t=16)),
                              axis.text.y = element_text(size = 40, margin = margin(r=16)),
                              axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                              axis.title.y = element_text(size = 60, margin = margin(r=40)))
                
                ##Time series points w/ smooth line (grouped by treatment)
                model_plot2 <- ggplot(data = model_data, aes(x = Month, y = Composite_Albedo, color = Treatment, group = Treatment)) +
                        geom_point() +
                        stat_summary(fun=mean,geom="line",lwd=2,aes(group=Treatment)) +
                        ggtitle("Monthly albedo estimates for SustHerb study sites") +
                                labs(x = "Month", y = "Albedo") +
                                scale_x_discrete(limits=c(1:12)) +                               
                                scale_color_manual(values=wes_palette(n=2, name="FantasticFox1")) +
                                theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                                      legend.title = element_text(size = 40),
                                      legend.text = element_text(size = 36),
                                      axis.text.x = element_text(size = 44, margin = margin(t=16)),
                                      axis.text.y = element_text(size = 40, margin = margin(r=16)),
                                      axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                                      axis.title.y = element_text(size = 60, margin = margin(r=40)))
                
                #Grouped boxplot
                model_data$Month <- as.factor(model_data$Month)
                model_plot3 <- ggplot(data = model_data, aes(x = Month, y = Composite_Albedo, fill = Treatment)) +
                        geom_boxplot() +
                        ggtitle("Monthly albedo estimates for SustHerb study sites") +
                        labs(x = "Month", y = "Albedo") +
                        scale_fill_manual(values=wes_palette(n=2, name="FantasticFox1")) +
                        theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                              legend.title = element_text(size = 40),
                              legend.text = element_text(size = 36),
                              axis.text.x = element_text(size = 44, margin = margin(t=16)),
                              axis.text.y = element_text(size = 40, margin = margin(r=16)),
                              axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                              axis.title.y = element_text(size = 60, margin = margin(r=40)))
                
                #Density plot of albedo estimates by treatment
                model_hist <- ggplot(data = model_data, aes(x = Composite_Albedo, fill = Treatment, group = Treatment)) +
                        geom_histogram(aes(y=..density..), bins = 30, alpha=1, position="identity") +
                        geom_density(alpha= 0.5) +
                        ggtitle("Frequency of Albedo Values") +
                        labs(x = "Albedo", y = "Frequency") +
                        theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                              legend.title = element_text(size = 40),
                              legend.text = element_text(size = 36),
                              axis.text.x = element_text(size = 44, margin = margin(t=16)),
                              axis.text.y = element_text(size = 40, margin = margin(r=16)),
                              axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                              axis.title.y = element_text(size = 60, margin = margin(r=40)))
                
                #Density of albedo estimates (log transformed)
                model_hist_log <- ggplot(data = model_data, aes(x = Composite_Albedo, fill = Treatment, group = Treatment)) +
                        geom_histogram(aes(y=..density..), bins = 30, alpha=1, position="identity") +
                        geom_density(alpha= 0.5) +
                        ggtitle("Frequency of Albedo Values") +
                        labs(x = "log(Albedo)", y = "Frequency") +
                        theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                              legend.title = element_text(size = 40),
                              legend.text = element_text(size = 36),
                              axis.text.x = element_text(size = 44, margin = margin(t=16)),
                              axis.text.y = element_text(size = 40, margin = margin(r=16)),
                              axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                              axis.title.y = element_text(size = 60, margin = margin(r=40))) +
                        scale_x_continuous(trans = 'log10')
                
              
#END EXPLORE DATA -----------------------------------------------------------------------------
                
                
                
                
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
                
                
                
                
#WRITE OUTPUT  ----------------------------------------------------------------------------

        #Write CSV to Output Folder
        write.csv(model_data, file = '1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/albedo_estimates_approach_1.csv', row.names = TRUE)
        
        #Export albedo boxplot as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/albedo_boxplot_approach_1.png",
            width = 2000,
            height = 2000,
            units = "px",
            bg = "white")
        model_plot1
        dev.off()
        
        #Export time series plot as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/albedo_time_series_approach_1.png",
            width = 3000,
            height = 2000,
            units = "px",
            bg = "white")
        model_plot2
        dev.off()
        
        #Export grouped boxplot as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/albedo_grouped_boxplot_approach_1.png",
            width = 3000,
            height = 2000,
            units = "px",
            bg = "white")
        model_plot3
        dev.off()
        
        #Export histogram as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/albedo_histogram_approach_1.png",
            width = 2500,
            height = 2000,
            units = "px",
            bg = "white")
        model_hist
        dev.off()


#END WRITE OUTPUT-------------------------------------------------------------------------               
        
       
