## Script to calculate albedo estimates for each relevant SustHerb site
## This script uses the albedo model generated by Cherubini et al. 


##PACKAGES ----------------------------------------------------------------------------------------

        #Packages for general data manipulation + visualization
        library(ggplot2)
        library(dplyr)
        library(RColorBrewer)
        library(wesanderson)
        library(sp)
        library(raster)
        library(GGally)
        library(lattice)
        library(gmodels)

###END PACKAGES ----------------------------------------------------------------------------------------




#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\




#INITIAL DATA IMPORT + FORMATTING ----------------------------------------------------------------------

        ## SITE DATA

                #Get 'cleaned' site data from adjacent 'Sites' folder
                site_data <- read.csv('1_Albedo_Exclosures/Data/SustHerb_Site_Data/cleaned_data/cleaned_data.csv', header = TRUE)

        ## SUBPLOT VOLUMES
                
                #Get plot volume estimates
                plot_volumes <- read.csv('1_Albedo_Exclosures/Approach_1/Output/Tree_Volumes/tree_volumes_approach_1.csv', header = TRUE)
                
                #Fix Singsås string
                plot_volumes$LocalityName[plot_volumes$LocalityName == "singsås"] <- "singsaas"
        
        ## SENORGE SWE/TEMP DATA
                
                #Add monthly SWE averages from seNorge
                swe <- read.csv('1_Albedo_Exclosures/Universal/Output/2016_Climate_Data/monthly_avg_swe_2016.csv', header = TRUE)
                
                #Add monthly temperature averages from seNorge
                temps <- read.csv('1_Albedo_Exclosures/Universal/Output/2016_Climate_Data/monthly_avg_temp_2016.csv', header = TRUE)
                
                        #Convert temps from celsius (C) to kelvin (K)
                        for( i in 1:length(temps$X)){
                                #K = C + 273.15
                                temps[i, "Avg_Temp_C"] <- temps[i, "Avg_Temp_C"] + 273.15
                        }
                
                        #Rename column from C to K
                        colnames(temps)[9] <- "Avg_Temps_K"
                
                #Isolate to 2016 data only only
                swe <- swe[swe$Year == "2016",]
                temps <- temps[temps$Year == "2016",]
                        
        #HERBIVORE DENSITY DATA
                        
                #Read in herbivore biomass data (2015) from SpatialPolygons object (isolate dataframe)
                hbiomass_shp <- shapefile("2_Albedo_Regional/Data/Herbivore_Densities/NorwayLargeHerbivores")
                
                #Pull out dataframe
                hbiomass <- hbiomass_shp@data
                
                #Isolate to 2015 data
                hbiomass2015<- cbind(hbiomass[,c(1:10)], hbiomass$Ms_2015, hbiomass$Rd__2015, hbiomass$R_d_2015)
                        
        ## SUSTHERB SITE PRODUCTIVITY
                        
                #Productivity Data
                productivity <- read.csv('1_Albedo_Exclosures/Data/SustHerb_Site_Data/productivity_all_sites.csv', header = TRUE)
                productivity$LocalityName <- tolower(productivity$LocalityName)
                
                        #Correct LocalityName items in productivity CSV
                        
                                #Didrik Holmsen
                                productivity$LocalityName[productivity$LocalityName == "didrik holmsen"] <- "didrik_holmsen"
                                
                                #Fet 3
                                productivity$LocalityName[productivity$LocalityName == "fet 3"] <- "fet_3"
                                
                                #Fritsøe 1
                                productivity$LocalityName[productivity$LocalityName == "fritsøe1"] <- "fritsoe1"
                                
                                #Fritsøe 2
                                productivity$LocalityName[productivity$LocalityName == "fritsøe2"] <- "fritsoe2"
                                
                                #Halvard Pramhus
                                productivity$LocalityName[productivity$LocalityName == "halvard pramhus"] <- "halvard_pramhus"
                                
                                #Singsaas
                                productivity$LocalityName[productivity$LocalityName == "singsås"] <- "singsaas"
                                
                                #Stangeskovene Aurskog
                                productivity$LocalityName[productivity$LocalityName == "stangeskovene aurskog"] <- "stangeskovene_aurskog"
                                
                                #Stangeskovene Eidskog
                                productivity$LocalityName[productivity$LocalityName == "stangeskovene eidskog"] <- "stangeskovene_eidskog"
                                
                                #Stig Dahlen
                                productivity$LocalityName[productivity$LocalityName == "stig dæhlen"] <- "stig_dahlen"
                                
                                #Truls Holm
                                productivity$LocalityName[productivity$LocalityName == "truls holm"] <- "truls_holm"
        
        ## SUSTHERB TREE SPECIES PROPORTIONS (At the PLOT level)
        
                #Tree density data for Trøndelag, Telemark, and Hedmark (including 2019 data)
                tree_data <- read.csv('1_Albedo_Exclosures/Universal/Output/Tree_Species_Proportions/tree_species_proportions_plot_level.csv', header = TRUE)
                tree_data <- tree_data[,2:7]
                
                #Filter tree data to 2016 (to correspond with detailed SUSTHERB tree data)
                tree_data <- tree_data[tree_data$Year == 2016,]

                        #Filter out unused SustHerb sites (since detailed 2016 tree data is only available in Trondelag)
                
                                #Convert site codes to factors
                                tree_data$LocalityCode <- as.factor(tree_data$LocalityCode)
                                plot_volumes$LocalityCode <- as.factor(plot_volumes$LocalityCode)
                                
                                #Get vector of levels for sites that will be used (n = 30; only in Trøndelag)
                                used_sites <- levels(plot_volumes$LocalityCode)
                        
                                #Filter tree data to used sites
                                tree_data <- tree_data[tree_data$LocalityCode %in% used_sites,]
                                tree_data$LocalityCode <- as.factor(as.character(tree_data$LocalityCode))
                        
                
#END INITIAL DATA IMPORT + FORMATTING ------------------------------------------------------------------

        


#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\




#CALCULATE MONTHLY ALBEDOS -----------------------------------------------------------------------------
        
        #Albedo function
                                
                #Source albedo model function
                source("3_Albedo_Model/albedo_model_volume.R")
                                
                #Blank dataframe to hold final albedo values
                albedo2 <- data.frame("Month" = integer(),
                                      "Spruce_Albedo" = double(),
                                      "Pine_Albedo" = double(),
                                      "Birch_Albedo" = double(),
                                      "Composite_Albedo" = double(),
                                      "LocalityName" = factor(),
                                      "SWE_mm" = double(),
                                      "Temp_K" = double())
                                
                #For each site, run albedo model function w/ relevant arguments
                for(i in 1:length(plot_volumes$LocalityCode)){
                        
                        #Get site code
                        a <- as.character(plot_volumes[i, "LocalityCode"][[1]])
                        
                        #Get site name
                        b <- as.character(plot_volumes[i, "LocalityName"][[1]])
                        
                        #Get treatment
                        c <- plot_volumes[i, "Treatment"]
                        
                        #Get corresponding function arguments
                        
                                #Volume (IMPORTANT: USE VOLUME/AREA VALUE - m3/ha - THIS IS THE CORRECT PARAMETER IN THE MODEL)
                                a_vol <- plot_volumes$Volume_m3_ha[plot_volumes$LocalityCode == a]
                                
                                #Spruce %
                                a_spruce <- tree_data$Prop_spruce[tree_data$LocalityCode == a]
                                
                                #Pine %
                                a_pine <- tree_data$Prop_pine[tree_data$LocalityCode == a]
                                
                                #Birch/Deciduous %
                                a_birch <- tree_data$Prop_birch[tree_data$LocalityCode == a]
                                
                                #NOTE: The SWE and Temp datasets only have data for the 'browsed' plots
                                ## However, it is assuemd that the exclosures have the same SWE & Temp data
                                ### The code below handles this issue - for all exclosures, SWE/Temp data
                                #### from open plots is used
                                
                                        #If exclosure, get LocalityCode for corresponding open plot
                                        if(c == "UB"){
                                                
                                              d <- plot_volumes$LocalityCode[plot_volumes$LocalityName == b & plot_volumes$Treatment == 'B']
                                              
                                              #Temps
                                              a_temps <- temps$Avg_Temps_K[temps$LocalityCode == d]
                                              
                                              #SWE
                                              a_swe <- swe$SWE_mm[swe$LocalityCode == d]
                                                      
                                        } else if (c == "B"){
                                                
                                                #Temps
                                                a_temps <- temps$Avg_Temps_K[temps$LocalityCode == a]
                                                
                                                #SWE
                                                a_swe <- swe$SWE_mm[swe$LocalityCode == a]
                                        }
                                
                                
                        #Run function with necessary arguments
                        albedo1 <- albedoVol(site = a,
                                             localityName = b,
                                             treatment = c,
                                             vol = a_vol,
                                             temp = a_temps,
                                             swe = a_swe,
                                             spruce = a_spruce,
                                             pine = a_pine,
                                             birch = a_birch)
                        
                        albedo2 <- rbind(albedo2, albedo1)
                        
                }
                                
#END CALCULATE MONTHLY ALBEDOS -------------------------------------------------------------------------
                
                
                

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\




#FINALIZE DATA -----------------------------------------------------------------------------------------

                
        ##Coalesce all data into single dataframe (for analysis) -------------------
                
                #Add new columns
                albedo2$Region = ''
                albedo2$Experiment_ID = ''
                albedo2$District_ID = ''
                albedo2$Longitude = ''
                albedo2$Latitude = ''
                albedo2$Clearcut_Year = ''
                albedo2$Exclosure_Start_Year = ''
                albedo2$Productivity_Index = ''
                albedo2$Prop_Pine_2016 = ''
                albedo2$Prop_Birch_2016 = ''
                albedo2$Prop_Spruce_2016 = ''
                albedo2$Plot_Volume_m3_2016 = ''
                albedo2$Plot_Volume_m3ha_2016 = ''
                albedo2$Moose_Density = ''
                albedo2$Red_Deer_Density = ''
                albedo2$Roe_Deer_Density = ''
                albedo2$CH_Mean = ''
                albedo2$CH_Median = ''
                albedo2$CH_SD = ''
                albedo2$CH_IQR = ''
                albedo2$CH_MAD = ''
                
                #Define 'model_data' df for analysis
                model_data <- albedo2
                
                #Add relevant data for new columns
                for(i in 1:nrow(model_data)){
                        
                        print(i)
                        
                        #Get locality code
                        loc <- model_data[i, "LocalityCode"]
                        
                        #Get site name
                        sn <- model_data[i, "LocalityName"]
                        
                        #Get corresponding 'region' from site data & add
                        region <- site_data$Region[site_data$LocalityCode == loc]
                        model_data[i, "Region"] <- region
                        
                        #Get corresponding experiment ID & add
                        exp_id <- site_data$ExperimentID[site_data$LocalityCode == loc]
                        model_data[i, "Experiment_ID"] <- exp_id
                        
                        #Get kommune number (district ID) & add
                        kn <- site_data$DistrictID[site_data$LocalityCode == loc]
                        model_data[i, "District_ID"] <- kn
                        
                        #Longitude
                        lon <- site_data$Longitude[site_data$LocalityCode == loc]
                        model_data[i, "Longitude"] <- lon
                        
                        #Latitude
                        lat <- site_data$Latitude[site_data$LocalityCode == loc]
                        model_data[i, "Longitude"] <- lon
                        
                        #Clearcut Year
                        ccy <- site_data$Clear.cut[site_data$LocalityCode == loc]
                        model_data[i, "Clearcut_Year"] <- ccy
                        
                        #Exclosure Start Year
                        esy <- site_data$Year.initiated[site_data$LocalityCode == loc]
                        model_data[i, "Exclosure_Start_Year"] <- esy
                        
                        #Get corresponding 'productivity' & add
                        prod <- productivity$Productivity[productivity$LocalityName == sn]
                        model_data[i, "Productivity_Index"] <- prod
                        
                        #Prop of pine in 2016
                        pp2016 <- tree_data$Prop_pine[tree_data$LocalityCode == loc]
                        model_data[i, "Prop_Pine_2016"] <- pp2016
                        
                        #Prop of birch in 2016
                        bp2016 <- tree_data$Prop_birch[tree_data$LocalityCode == loc]
                        model_data[i, "Prop_Birch_2016"] <- bp2016
                        
                        #Prop of spruce in 2016
                        sp2016 <- tree_data$Prop_spruce[tree_data$LocalityCode == loc]
                        model_data[i, "Prop_Spruce_2016"] <- sp2016
                        
                        #Plot volume sum in 2016
                        vs2016 <- plot_volumes$Volume_m3[plot_volumes$LocalityCode == loc]
                        model_data[i, "Plot_Volume_m3_2016"] <- vs2016
                        
                        #Plot volume/ha in 2016
                        vs_ha2016 <- plot_volumes$Volume_m3_ha[plot_volumes$LocalityCode == loc]
                        model_data[i, "Plot_Volume_m3ha_2016"] <- vs_ha2016
                        
                        #Moose density
                        md <- hbiomass2015$`hbiomass$Ms_2015`[hbiomass2015$KOMMUNE == kn]
                        model_data[i, "Moose_Density"] <- md
                        
                        #Red deer density
                        rd <- hbiomass2015$`hbiomass$Rd__2015`[hbiomass2015$KOMMUNE == kn]
                        model_data[i, "Red_Deer_Density"] <- rd
                        
                        #Roe deer density
                        rdd <- hbiomass2015$`hbiomass$R_d_2015`[hbiomass2015$KOMMUNE == kn]
                        model_data[i, "Roe_Deer_Density"] <- rdd
                        
                        #Canopy Height Mean
                        chmean <- site_data$Mean[site_data$LocalityCode == loc]
                        model_data[i, "CH_Mean"] <- chmean
                        
                        #Canopy Height Mean
                        chmedian <- site_data$Median[site_data$LocalityCode == loc]
                        model_data[i, "CH_Median"] <- chmedian
                        
                        #Canopy Height SD
                        chsd <- site_data$SD[site_data$LocalityCode == loc]
                        model_data[i, "CH_SD"] <- chsd
                        
                        #Canopy Height IQR
                        chiqr <- site_data$IQR[site_data$LocalityCode == loc]
                        model_data[i, "CH_IQR"] <- chiqr
                        
                        #Canopy height MAD 
                        mad <- site_data$MAD[site_data$LocalityCode == loc]
                        model_data[i, "CH_MAD"] <- mad
                        
                        
                        
                }
                
                model_data$Treatment <- as.factor(model_data$Treatment)
                model_data$Productivity_Index <- as.numeric(model_data$Productivity_Index)
                model_data$Month <- as.numeric(model_data$Month)
                model_data$LocalityCode <- as.character(model_data$LocalityCode)
                model_data$Moose_Density <- as.numeric(model_data$Moose_Density)
                model_data$Red_Deer_Density <- as.numeric(model_data$Red_Deer_Density)
                model_data$Roe_Deer_Density <- as.numeric(model_data$Roe_Deer_Density)

        #Create "melted" version of the data (so I can plot and facet by species-specific albedo) ---------
                
                #"Expand" model data - create 3 copies of each row (3 species)
                model_melt <- model_data[rep(seq_len(nrow(model_data)), each = 3), ]
                
                #Add new columns for species + albedo
                model_melt$Albedo <- as.numeric('')
                model_melt$Species <- rep(c("Spruce","Pine","Birch"), each = 1, times = nrow(model_melt)/3)
                
                #Loop through all rows and add relevant albedo value
                for(i in 1:nrow(model_melt)){
                        
                        spec <- model_melt[i, "Species"]
                        model_melt[i, "Albedo"] <- model_melt[i, paste(spec, "_Albedo", sep = "")]
                        
                }
                
                #Remove unused columns
                model_melt <- model_melt[,c(1,6:33)]

                
#END FINALIZE DATA -----------------------------------------------------------------------------------------                
                
                
        
                        
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
                
                
                
                
#EXPLORE DATA --------------------------------------------------------------------------------
                
        ##Explore data w/ plots
        pd <- position_dodge(0.2)
                
                #Composite albedo ----
                
                        
                
                        #Scatterplot
                        model_data$Month <- as.integer(model_data$Month)
                        plot_c1 <- ggplot(data = model_data, aes(x = Month, y = Composite_Albedo, color = Treatment)) +
                                        geom_point(position = pd) +
                                        geom_smooth(span = 0.1, se = F) +
                                        ggtitle("Composite Albedo by Treatment (n = 15)") +
                                        labs(y = "Composite Albedo") +
                                        scale_x_discrete(limits = c(1,12), breaks = c(1,2,3,4,5,6,7,8,9,10,11,12)) +
                                        theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                                              legend.title = element_text(size = 40),
                                              legend.text = element_text(size = 36),
                                              axis.text.x = element_text(size = 44, margin = margin(t=16)),
                                              axis.text.y = element_text(size = 40, margin = margin(r=16)),
                                              axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                                              axis.title.y = element_text(size = 60, margin = margin(r=40)))
                
                        #Boxplot Time Series
                        model_data$Month <- as.factor(model_data$Month)
                        plot_c2 <- ggplot(data = model_data, aes(x = Month, y = Composite_Albedo, fill = Treatment)) +
                                geom_boxplot() +
                                ggtitle("Composite Albedo by Treatment (n = 15)") +
                                labs(y = "Composite Albedo") +
                                theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                                      legend.title = element_text(size = 40),
                                      legend.text = element_text(size = 36),
                                      axis.text.x = element_text(size = 44, margin = margin(t=16)),
                                      axis.text.y = element_text(size = 40, margin = margin(r=16)),
                                      axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                                      axis.title.y = element_text(size = 60, margin = margin(r=40)))
                
                #Species-specific albedos ----
                
                        #Scatterplot
                        plot1 <- ggplot(data = model_melt, aes(x = Month, y = Albedo, color = Treatment)) +
                                        geom_point(position = pd) +
                                        facet_wrap(~ Species, ncol = 1) +
                                        geom_smooth(span = 0.1, se = F) +
                                        ggtitle("Species-Specific Albedo by Treatment (n = 15)") +
                                        scale_x_discrete(limits = c(1,12), breaks = c(1,2,3,4,5,6,7,8,9,10,11,12)) +
                                        theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                                              legend.title = element_text(size = 40),
                                              legend.text = element_text(size = 36),
                                              axis.text.x = element_text(size = 44, margin = margin(t=16)),
                                              axis.text.y = element_text(size = 40, margin = margin(r=16)),
                                              axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                                              axis.title.y = element_text(size = 60, margin = margin(r=40)))
                        
                        #Mean values w/ error bars
                        
                                #Aggregate mean albedo values by Treatment and Species
                                means <- aggregate(model_melt$Albedo, by = list(Treatment = model_melt$Treatment, Species = model_melt$Species, Month = model_melt$Month), FUN = mean)
                
                                #Aggregate SE values by Treatment and Spcies
                                sd <- aggregate(model_melt$Albedo, by = list(Treatment = model_melt$Treatment, Species = model_melt$Species, Month = model_melt$Month), FUN = sd)
                                
                                #Bind together 
                                stat <- cbind(means, sd[4])
                                colnames(stat)[4] <- "Mean_Albedo"
                                colnames(stat)[5] <- "SD"
                                
                                #Plot
                                stat$Month <- as.integer(stat$Month)
                                plot2 <- ggplot(data = stat, aes(x = Month, y = Mean_Albedo, color = Treatment, group = Treatment)) +
                                                geom_errorbar(aes(ymin = Mean_Albedo-SD, ymax = Mean_Albedo+SD), colour="black", width=.3, position=pd) +
                                                geom_line(position = pd, lwd = 2) +
                                                geom_point(position = pd, size=6) +
                                                facet_wrap(~ Species, ncol = 1) +
                                                ggtitle("Average Species-Specific Albedo by Treatment (n = 15)") +
                                                labs(y = "Mean Albedo") +
                                                scale_x_discrete(limits = c(1,12), breaks = c(1,2,3,4,5,6,7,8,9,10,11,12)) +
                                                theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                                                      legend.title = element_text(size = 40),
                                                      legend.text = element_text(size = 36),
                                                      strip.text = element_text(size = 36),
                                                      axis.text.x = element_text(size = 44, margin = margin(t=16)),
                                                      axis.text.y = element_text(size = 40, margin = margin(r=16)),
                                                      axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                                                      axis.title.y = element_text(size = 60, margin = margin(r=40)))
                      
                                
        #Plot "exclosure effect" (excl-open) ----------
        
                #Composite ----
                                
                        #Create new df w/ excl-open for each LocalityName
                        
                                #Aggregate
                                comp_albedo_diff <- aggregate(model_data$Composite_Albedo,
                                                         by = list(Month = model_data$Month,
                                                                   LocalityName = model_data$LocalityName),
                                                         FUN = diff)
                                
                                names(comp_albedo_diff)[3] <- "Albedo_Diff_Excl_Open"
                                comp_albedo_diff$Albedo_Diff_Excl_Open <- as.numeric(comp_albedo_diff$Albedo_Diff_Excl_Open)
                                
                                #Plot
                                
                                        #Versus productivity index
                                
                                                #Add productivity index to df
                                                comp_albedo_diff$Productivity <- ''
                                                for(i in 1:nrow(comp_albedo_diff)){
                                                        
                                                        locale <- comp_albedo_diff[i, "LocalityName"]
                                                        comp_albedo_diff[i, "Productivity"] <- productivity$Productivity[productivity$LocalityName == locale][1]
                                                
                                                }
                                                
                                                comp_albedo_diff$Productivity <- as.numeric(comp_albedo_diff$Productivity)
                                                
                                                #Plot
                                                plot_prod <- ggplot(data = comp_albedo_diff, aes(x = Productivity, y = Albedo_Diff_Excl_Open)) +
                                                                geom_point() +
                                                                facet_wrap(~ Month) +
                                                                ggtitle("Treatment Effect vs. Productivity Index (n = 15)\nFaceted by Month") +
                                                                scale_x_continuous(limits = c(0,0.3), breaks = c(0,0.1,0.2,0.3)) +
                                                                theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                                                                      legend.title = element_text(size = 40),
                                                                      legend.text = element_text(size = 36),
                                                                      axis.text.x = element_text(size = 44, margin = margin(t=16)),
                                                                      axis.text.y = element_text(size = 40, margin = margin(r=16)),
                                                                      axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                                                                      axis.title.y = element_text(size = 60, margin = margin(r=40)))
                                
                                        #Means w/ CI
                                
                                                #Create means df
                                                comp_albedo_means <- aggregate(comp_albedo_diff$Albedo_Diff_Excl_Open,
                                                                               by = list(Month = comp_albedo_diff$Month),
                                                                               FUN = mean)
                                                
                                                comp_albedo_means$CI_Lower <- ''
                                                comp_albedo_means$CI_Upper <- ''
                                                
                                                #Add CIs for each month of data
                                                for(i in 1:12){
                                                        
                                                        comp_albedo_means[i, "CI_Lower"] <- ci(comp_albedo_diff$Albedo_Diff_Excl_Open[comp_albedo_diff$Month == i])[2]
                                                        comp_albedo_means[i, "CI_Upper"] <- ci(comp_albedo_diff$Albedo_Diff_Excl_Open[comp_albedo_diff$Month == i])[3]
                                                        
                                                }
                                        
                                                
                                                colnames(comp_albedo_means)[2] <- "Mean_Diff"
                                                comp_albedo_means$Month <- as.integer(comp_albedo_means$Month)
                                                comp_albedo_means$Mean_Diff <- as.numeric(comp_albedo_means$Mean_Diff)
                                                comp_albedo_means$CI_Lower <- as.numeric(comp_albedo_means$CI_Lower)
                                                comp_albedo_means$CI_Upper <- as.numeric(comp_albedo_means$CI_Upper)
                                                
                                                #Plot
                                                plot_diff_1 <- ggplot(data = comp_albedo_means, aes(x = Month, y = Mean_Diff)) +
                                                                        geom_errorbar(aes(ymin = CI_Lower, ymax = CI_Upper), colour="black", width=.4) +
                                                                        geom_line(lwd = 1.3) +
                                                                        geom_point(size=6) +
                                                                        ggtitle("Avg. Treatment Effect on Composite Albedo\n(Excl. - Open) - Bars = 95% CIs") +
                                                                        labs(y = "Average Composite Albedo Difference\n(Excl. - Open)") +
                                                                        scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12)) +
                                                                        scale_y_continuous(limits = c(-0.05, 0.05)) +
                                                                        geom_hline(yintercept=0, linetype="dashed", color = "#666666") + 
                                                                        theme(plot.title = element_text(hjust = 0.5, size = 60, margin = margin(t = 40, b = 40)),
                                                                              legend.title = element_text(size = 40),
                                                                              legend.text = element_text(size = 36),
                                                                              strip.text = element_text(size = 36),
                                                                              axis.text.x = element_text(size = 44, margin = margin(t=16)),
                                                                              axis.text.y = element_text(size = 40, margin = margin(r=16)),
                                                                              axis.title.x = element_text(size = 60, margin = margin(t=40, b = 40)),
                                                                              axis.title.y = element_text(size = 60, margin = margin(r=40)))
                                                
                                        
                                
                                
                                
                                
                                
                #Species-specific ----
                
                        #Create new df w/ excl-open for each LocalityName
                                
                                #Aggregate
                                spec_albedo_diff <- aggregate(model_melt$Albedo,
                                                              by = list(Month = model_melt$Month,
                                                                        LocalityName = model_melt$LocalityName,
                                                                        Species = model_melt$Species),
                                                              FUN = diff)
                                
                                names(spec_albedo_diff)[4] <- "Albedo_Diff_Excl_Open"
                                spec_albedo_diff$Albedo_Diff_Excl_Open <- as.numeric(spec_albedo_diff$Albedo_Diff_Excl_Open)
                                
                                #Means w/ SD
                                
                                        #Create means df
                                        spec_albedo_means <- aggregate(spec_albedo_diff$Albedo_Diff_Excl_Open,
                                                                       by = list(Month = spec_albedo_diff$Month,
                                                                                 Species = spec_albedo_diff$Species),
                                                                       FUN = mean)
                                        
                                        spec_albedo_means$CI_Lower <- ''
                                        spec_albedo_means$CI_Upper <- ''
                                        
                                        #Add CIs for each month of data (and each to each species)
                                        for(i in 1:12){
                                                
                                                #CI Lower
                                                spec_albedo_means$CI_Lower[spec_albedo_means$Species == "Spruce" & spec_albedo_means$Month == i] <- ci(spec_albedo_diff$Albedo_Diff_Excl_Open[spec_albedo_diff$Species == "Spruce" & spec_albedo_diff$Month == i])[2]
                                                spec_albedo_means$CI_Lower[spec_albedo_means$Species == "Pine" & spec_albedo_means$Month == i] <- ci(spec_albedo_diff$Albedo_Diff_Excl_Open[spec_albedo_diff$Species == "Pine" & spec_albedo_diff$Month == i])[2]
                                                spec_albedo_means$CI_Lower[spec_albedo_means$Species == "Birch" & spec_albedo_means$Month == i] <- ci(spec_albedo_diff$Albedo_Diff_Excl_Open[spec_albedo_diff$Species == "Birch" & spec_albedo_diff$Month == i])[2]
                                                
                                                #CI Upper
                                                spec_albedo_means$CI_Upper[spec_albedo_means$Species == "Spruce" & spec_albedo_means$Month == i] <- ci(spec_albedo_diff$Albedo_Diff_Excl_Open[spec_albedo_diff$Species == "Spruce" & spec_albedo_diff$Month == i])[3]
                                                spec_albedo_means$CI_Upper[spec_albedo_means$Species == "Pine" & spec_albedo_means$Month == i] <- ci(spec_albedo_diff$Albedo_Diff_Excl_Open[spec_albedo_diff$Species == "Pine" & spec_albedo_diff$Month == i])[3]
                                                spec_albedo_means$CI_Upper[spec_albedo_means$Species == "Birch" & spec_albedo_means$Month == i] <- ci(spec_albedo_diff$Albedo_Diff_Excl_Open[spec_albedo_diff$Species == "Birch" & spec_albedo_diff$Month == i])[3]

                                        }
                                        
                                        colnames(spec_albedo_means)[3] <- "Mean_Diff"
                                        spec_albedo_means$Month <- as.integer(spec_albedo_means$Month)
                                        spec_albedo_means$Mean_Diff <- as.numeric(spec_albedo_means$Mean_Diff)
                                        spec_albedo_means$CI_Lower <- as.numeric(spec_albedo_means$CI_Lower)
                                        spec_albedo_means$CI_Upper <- as.numeric(spec_albedo_means$CI_Upper)
                                        
                                        #Plot
                                        plot_diff_2 <- ggplot(data = spec_albedo_means, aes(x = Month, y = Mean_Diff, color = Species, group = Species)) +
                                                                geom_errorbar(aes(ymin = CI_Lower, ymax = CI_Upper), colour="black", width=.4, position = pd) +
                                                                geom_line(lwd = 1.3) +
                                                                geom_point(size=6, position = pd, aes(shape = Species)) +
                                                                ggtitle("Effect of Exclosure on Albedo (n = 15)") +
                                                                labs(y = "Mean Albedo Difference\n(Excl. - Open)") +
                                                                scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12)) +
                                                                scale_y_continuous(limits = c(-0.03, 0.015)) +
                                                                geom_hline(yintercept=0, linetype="dashed", color = "#666666") + 
                                                                theme_bw() +
                                                                theme(plot.title = element_text(hjust = 0.5, size = 42, margin = margin(t = 40, b = 40)),
                                                                      legend.title = element_text(size = 32),
                                                                      legend.text = element_text(size = 28),
                                                                      axis.text.x = element_text(size = 34, margin = margin(t=16)),
                                                                      axis.text.y = element_text(size = 34, margin = margin(r=16)),
                                                                      axis.title.x = element_text(size = 40, margin = margin(t=40, b = 40)),
                                                                      axis.title.y = element_text(size = 40, margin = margin(r=40)))
                                        
                                        #Plot
                                        plot_diff_3 <- ggplot(data = spec_albedo_means, aes(x = Month, y = Mean_Diff, color = Species, group = Species)) +
                                                geom_errorbar(aes(ymin = CI_Lower, ymax = CI_Upper), colour="black", width=.4, position = pd) +
                                                geom_line(lwd = 1.3) +
                                                geom_point(size=6, position = pd, aes(shape = Species)) +
                                                ggtitle("Effect of Exclosure on Albedo (n = 15)") +
                                                labs(y = "Mean Albedo Difference\n(Excl. - Open)") +
                                                scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12)) +
                                                scale_y_continuous(limits = c(-0.03, 0.015)) +
                                                geom_hline(yintercept=0, linetype="dashed", color = "#666666") + 
                                                facet_wrap(~ Species, nrow = 3) +
                                                theme_bw() +
                                                theme(plot.title = element_text(hjust = 0.5, size = 44, margin = margin(t = 40, b = 40)),
                                                      legend.title = element_text(size = 32),
                                                      legend.text = element_text(size = 28),
                                                      axis.text.x = element_text(size = 34, margin = margin(t=16)),
                                                      axis.text.y = element_text(size = 34, margin = margin(r=16)),
                                                      axis.title.x = element_text(size = 42, margin = margin(t=40, b = 40)),
                                                      axis.title.y = element_text(size = 42, margin = margin(r=40)))
                                        
                                        
                        #Add "3rd variables" to spec_albedo_diff df
                                        
                                spec_albedo_diff$SWE <- ''
                                spec_albedo_diff$Temp <- ''
                                spec_albedo_diff$Productivity <- ''
                                
                                for(i in 1:nrow(spec_albedo_diff)){
                                        
                                        m <- spec_albedo_diff[i, "Month"]
                                        loc <- spec_albedo_diff[i, "LocalityName"]
                                        
                                        spec_albedo_diff[i, "SWE"] <- model_data$SWE_mm[model_data$Month == m & model_data$LocalityName == loc][1]
                                        spec_albedo_diff[i, "Temp"] <- model_data$Temp_K[model_data$Month == m & model_data$LocalityName == loc][1]
                                        spec_albedo_diff[i, "Productivity"] <- model_data$Productivity_Index[model_data$Month == m & model_data$LocalityName == loc][1]
                                }
                                
                                #Plot by 3rd variables ------
                                
                                        #SWE
                                        spec_albedo_diff$SWE <- as.numeric(spec_albedo_diff$SWE)
                                        ggplot(data = spec_albedo_diff, aes(x = SWE, y = Albedo_Diff_Excl_Open, color = Species)) +
                                                geom_point() +
                                                geom_smooth() +
                                                facet_wrap(~ Month)
                                        
                                                #NO REAL TREND ACROSS MONTHS
                                        
                                        #TEMP
                                        spec_albedo_diff$Temp <- as.numeric(spec_albedo_diff$Temp)
                                        ggplot(data = spec_albedo_diff, aes(x = Temp, y = Albedo_Diff_Excl_Open, color = Species)) +
                                                geom_point() +
                                                geom_smooth() +
                                                facet_wrap(~ Month)
                                        
                                        #Productivity
                                        spec_albedo_diff$Productivity <- as.numeric(spec_albedo_diff$Productivity)
                                        ggplot(data = spec_albedo_diff, aes(x = Productivity, y = Albedo_Diff_Excl_Open, color = Species)) +
                                                geom_point() +
                                                geom_smooth() +
                                                facet_wrap(~ Month)
                                
                                
                                                #NO STRONG TRENDS FOR THESE 3RD VARIABLES
                                        

                                
                                
                                
#END EXPLORE DATA -----------------------------------------------------------------------------
                
                
                
                
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
                
                
                
                
#WRITE OUTPUT  ----------------------------------------------------------------------------

        #Write CSV to Output Folder
        write.csv(model_data, file = '1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/albedo_estimates_approach_1.csv', row.names = TRUE)
        
        #Write Melted CSV to Output Folder        
        write.csv(model_melt, file = '1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/albedo_estimates_melted_approach_1.csv', row.names = TRUE)
        
        #Composite scatterplot as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_comp_timeseries.png",
            width = 2000,
            height = 2000,
            units = "px",
            bg = "white")
        plot_c1
        dev.off()
        
        #Composite boxplot as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_comp_boxplot.png",
            width = 2000,
            height = 2000,
            units = "px",
            bg = "white")
        plot_c2
        dev.off()
               
        #Species-specific scatterplot as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_timeseries.png",
            width = 2000,
            height = 2000,
            units = "px",
            bg = "white")
        plot1
        dev.off()
        
        #Species-specific means + SE as PNG
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_timeseries_means.png",
            width = 2000,
            height = 2000,
            units = "px",
            bg = "white")
        plot2
        dev.off()
        
        #Composite Treatment Effect Means + CI
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_comp_diff_means.png",
            width = 2000,
            height = 2000,
            units = "px",
            bg = "white")
        plot_diff_1
        dev.off()
        
        #Species-specific mean treatment effects + CI
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_spec_diff_means.png",
            width = 1600,
            height = 1200,
            units = "px",
            bg = "white")
        plot_diff_2
        dev.off()
        
        #Species-specific mean treatment effects + CI
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_spec_diff_means_facet.png",
            width = 1500,
            height = 1800,
            units = "px",
            bg = "white")
        plot_diff_3
        dev.off()
        
        #Treatment effects (not mean) by productivity
        png(filename = "1_Albedo_Exclosures/Approach_1/Output/Albedo_Estimates/approach_1_comp_diff_prod.png",
            width = 2000,
            height = 2000,
            units = "px",
            bg = "white")
        plot_prod
        dev.off()
        
        
#END WRITE OUTPUT-------------------------------------------------------------------------               
        
       
